extends:
  - "airbnb-base"
parser: typescript-eslint-parser
env:
  node: true
  es6: true
rules:
  no-unused-vars:
    - warn
  arrow-body-style:
    - off
  no-param-reassign:
    - warn
  no-empty-function:
    - warn
  no-underscore-dangle:
    - off
  class-methods-use-this:
    - off
  array-callback-return:
    - off
  import/prefer-default-export:
    - off
