language: node_js
node_js:
- 4

cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"

script:
- npm run lint
- npm run build
- npm test

deploy:
  provider: npm
  email: xuzhipei@gmail.com
  api_key:
    secure: NOxOe7pVshCBObtqzIj7WVmqw6zkwlF+RSIn4meWOsdOPOadX98G3pz8VlIGSKcaXq82Td/cVzkatAKEA0ooptL+HchLXdEy/GznDbjjx1Mh8w7DGKAsqrmXeV/TVIGgPCOdYqEdFyPba0Q/x1sMuyqzVVdWuo5B8mlGAeXQGs+WjMYlpuD6WvSUtdHgfeu66Ev8tC2VIUmjvNeZvjs7t8KIHuOdrY0GSHP89WX5UQI5uLyUOKbFU7xek1X3vbmj9PeD6Is9D4KyuvBTEIO7OXov1Y1rQxIt5R2UKsyKJJjuB1Yx3FAWCS5frvTE5hNTzAeN9DAA7GBRW8NaXpFO3b6abjtrUsUf5yqPQHtPMZiBETDkQIWfm2Vwhh1yY9Jr8WNm9bv0JvCRku1xQklUUseQpic7pZx+Bd91KZCuprd84J1ADhpoOU3XjZmjKaqRAgLR/KcNYUNdlG3sbr271U1toLFnQj87N2p0RwpM3VAgZpRAHuFGVb4FNIy0bWC/BUv2a+bvBypDupumhaFfzH1O3WeTtAnlwD9ZqUXCTl8MQTb9EOS6kPCyXAUN1ijh51SUMlsiYc3qT1wBf2pwXKF7YGP4dviMLXdkXaemviS1KP0WcvaFDqBtt4BlbmJWSKjnTgJtVm8TIb5k+BI35gxSnAE883fdoIvBdLpYsB4=
  on:
    tags: true
    repo: xizhibei/getui-rest-sdk
  skip_cleanup: true
